### ISSUE TITLE
Add ability to hide mode and layout

### ISSUE THREAD

**Issue by simonhughxyz** [kolunmi/sandbar#21]
It would be nice to be able to hide them with flags.

It would also be nice to hide mode when mode is normal and only show it when it is not.

**Comment by saifshahriar** [comment]
Also, it would be appreciated if we could customize what is shown there.

Example:
`[]=` instead of the `rivertile - left`

I don't use the small rectangle, instead I use the `alttagsdecoration` patch for DWM.

It would be nice if someone could explain a way to customise it like that.

![alttagsdecoration.png](https://github.com/user-attachments/assets/c5cebf3e-1448-4933-a7d8-c03610af845b)

**Comment by saifshahriar** [comment]
Nevermind. I was able to hack into the `sandbar.c` file and able to patch so the I have the same [alttagsdecoration](https://dwm.suckless.org/patches/alttagsdecoration/) functionality.

Basically everything related to this is in the `draw_frame(Bar *bar)` method.

Inside that, I looked for a conditional called `if (!hide_vacant && occupied)` and changed the pixman drawing stuff.

**If you don't want to see the `mode` and `layout`** just make the value of
```C
seat->mode = NULL;
bar->layout = NULL;
```
At the beginning of the `draw_frame(Bar *bar)`. This is a dirty hack. I am not sure if this would break anything. 🙇

**Comment by kolunmi** [comment]
> **If you don't want to see the `mode` and `layout`** just make the value of
> 
> ```c
> seat->mode = NULL;
> bar->layout = NULL;
> ```
> 
> At the beginning of the `draw_frame(Bar *bar)`. This is a dirty hack. I am not sure if this would break anything. 🙇

This will cause a memory leak, you can't just discard malloced memory like that

**Comment by kolunmi** [comment]
Fixed with e64a8b7
